export const mock = [
  {
    id: 1,
    title: '나우 유 씨 미 3',
    tag: '#애니메이션 #액션',
    ageRating: 15,
    releaseDate: '2024.01.15',
    runningTimeMinutes: 120,
  },
  {
    id: 2,
    title: '극장판 체인소 맨: 레제편',
    tag: '#애니메이션 #액션',
    ageRating: 15,
    releaseDate: '2024.01.15',
    runningTimeMinutes: 120,
  },
  {
    id: 3,
    title: '극장판 주술회전: 회옥·옥절',
    tag: '#애니메이션 #액션',
    ageRating: 15,
    releaseDate: '2024.01.15',
    runningTimeMinutes: 120,
  },
  {
    id: 4,
    title: '퍼스트 라이드',
    tag: '#드라마',
    ageRating: 15,
    releaseDate: '2024.01.15',
    runningTimeMinutes: 120,
  },
  {
    id: 5,
    title: '극장판 귀멸의 칼날: 무한성편',
    tag: '#애니메이션 #액션',
    ageRating: 15,
    releaseDate: '2024.01.15',
    runningTimeMinutes: 120,
  },
  {
    id: 6,
    title: '위키드',
    tag: '#드라마',
    ageRating: 15,
    releaseDate: '2024.01.15',
    runningTimeMinutes: 120,
  },
  {
    id: 7,
    title: '프레데터: 죽음의 땅',
    tag: '#드라마',
    ageRating: 15,
    releaseDate: '2024.01.15',
    runningTimeMinutes: 120,
  },
];
